language: node_js
node_js: -"4.0"
script:
  - echo "Deploying!"
before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
