# This is a basic workflow to help you get started with Actions
name: CI/CD
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # deploy job
  deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    # only run if build job complte successfully
    needs: [build]
    steps:
      # building the app before deploy
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install
      # build the app
      - name: Build the app artifact for prod
        run: npm run build --prod
      # ddeploy the app artifact to firebase
      - name: Deploy angular app to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
